name: DisguiseMe
version: '1.1'
main: org.hyperoil.playifkillers.disguiseMe
api-version: '1.21'
softdepend: ["PlaceholderAPI"]
depend: ["ProtocolLib"]
commands:
  disguise:
    description: disguise as something or someone...
    usage: /disguise <EntityType>
  pdisguise:
    description: disguise as something or someone...
    usage: /pdisguise playerName
  undisguise:
    description: undisguise
    usage: /undisguise
permissions:
  disguiseme.disguise:
    description: as the name suggests.
    default: op